### ISSUE TITLE
e-Translation not working in FREME basic

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/freme-docker#29]
I tried FREME basic and executed this command.

`curl -X POST "http://localhost:4000/e-translation/tilde?input=hello+world&informat=text&source-lang=en&target-lang=de"`

This is the error I get. Do I need to enable e-Translation somewhere, before I can use it?

```
{
  "exception": "eu.freme.common.exception.ExternalServiceFailedException",
  "path": "/e-translation/tilde",
  "message": "External service failed: {\"Message\":\"System not available for requested language pair\"}",
  "error": "Not Found",
  "status": 404,
  "timestamp": 1478170774511
}
```

**Comment by m1ci** [comment]
dont you have typo in the request? see `source-lang=entarget-lang=de` missing & sign between en and target-lang

**Comment by pheyvaer** [comment]
yeah, copy-pasted it bad from terminal. Updated the issue.

**Comment by jnehring** [comment]
I could reproduce the error on the dfki docker installation. The docker image used an old version of e-Translation. I updated it and created a new image of the broker. The issue is fixed on our installation. @pheyvaer can you please test if the problem is fixed on your side?

**Comment by pheyvaer** [comment]
When I do `docker-compose up -d` it says

```
freme_freme-mysql_1 is up-to-date
freme_freme-solr_1 is up-to-date
freme_freme-virtuoso_1 is up-to-date
freme_freme-broker_1 is up-to-date
```

And the issue still remains. Do I need to do sth special to make it download the newest version?

**Comment by jnehring** [comment]
Please try 

```
docker-compose stop freme-broker
docker-compose up -d --no-deps freme-broker
```

**Comment by pheyvaer** [comment]
I did that, but still get the same error.

**Comment by jnehring** [comment]
solved
