### ISSUE TITLE
Standard installation contains only English for NER

### ISSUE THREAD

**Issue by ghsnd** [freme-project/freme-docker#30]
According to the [documentation](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/use-freme-docker.html):

> standard: Contains all data of the basic installation. Further it contians DBPedia datasets in 7 languages (English, German, Dutch, French, Italian, Spanish, Russian) and the Europeana datasets.

I tried English, Dutch and French. E.g. for Dutch, I changed the following line in `config.env`:

    FREME_NER_LANGUAGES=nl

Only English works. For French and Dutch, this shows in the log files during startup:

```
ERROR   2016-11-03 16:09:08,321 [main] org.springframework.boot.SpringApplication  - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fremeNerEnrichment': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.elinker.core.api.java.FremeNer org.elinker.core.rest.FremeNerEnrichment.fremeNer; 
nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getFremeNer': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: /freme-package/freme-ner-models/wikiner-nl-ner-model.ser.gz (No such file or directory)
```

And indeed, only `wikiner-en-ner-model.ser.gz` is present.

**Comment by sandroacoelho** [comment]
Hi @ghsnd,  Thank you for the feedback. 

Before going to holidays, @jnehring has provided a demo just with English model and asked the team to validate the installation.

Have you found some issue during the installation with the English model?

He comes back on next week and will merge our issue #17, delivering  together with the other languages models.

Best,

**Comment by jnehring** [comment]
I could not reproduce this error. I guess it was fixed by one of the latest updates of the broker image. Please try it again.

**Comment by pheyvaer** [comment]
Executed the following commands, but still get the same error.
```
docker-compose stop freme-broker
docker-compose up -d --no-deps freme-broker
```

**Comment by jnehring** [comment]
The problem might be that docker does not download the latest images. Can you please login to the broker container and list the models? Perform these commands, the latest version shows this output:

```
u235827@rv2622:~$ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CR        EATED             STATUS              PORTS                    NAMES
09f4effa5504        fremeproject/freme-broker        "/bin/sh -c 'java -Xm"   40         minutes ago      Up 40 minutes       0.0.0.0:4000->8080/tcp   freme_freme-broke        r_1
c19d86ecc3a1        tenforce/virtuoso                "/bin/bash /virtuoso."   40         minutes ago      Up 40 minutes       1111/tcp, 8890/tcp       freme_freme-virtu        oso_1
33f395c0696d        fremeproject/freme-mysql-basic   "docker-entrypoint.sh"   40         minutes ago      Up 40 minutes       3306/tcp                 freme_freme-mysql        _1
5533bcb0b194        fremeproject/freme-solr          "docker-entrypoint.sh"   6         days ago          Up 46 minutes       0.0.0.0:4001->8983/tcp   freme_freme-solr_        1
8c7c84ae562c        fremedocker_solr-live            "docker-entrypoint.sh"   6         weeks ago         Up 6 weeks          0.0.0.0:8983->8983/tcp   fremedocker_solr-        live_1
c2694924034b        fremedocker_solr_dev             "docker-entrypoint.sh"   3         months ago        Up 7 days           0.0.0.0:8984->8983/tcp   fremedocker_solr_        dev_1
u235827@rv2622:~$ docker exec -it 09f4effa5504 /bin/sh
/ # ls /freme-ner-models/
wikiner-en-ner-model.ser.gz  wikiner-it-ner-model.ser.gz
wikiner-es-ner-model.ser.gz  wikiner-nl-ner-model.ser.gz
wikiner-fr-ner-model.ser.gz  wikiner-ru-ner-model.ser.gz
```

**Comment by jnehring** [comment]
Is the issue solved for you? Why did you close the issue?

**Comment by pheyvaer** [comment]
Yes, I had to pull the latest version of freme-broker from hub.docker.com using `docker pull`. So maybe it makes sense to update the FREME docker documentation because the following commands don't update the image to the latest version.

```
docker-compose stop freme-broker
docker-compose up -d --no-deps freme-broker
```

**Comment by jnehring** [comment]
ah great. i keep this issue open to remind me to update the documentation.

does this solve #29 also?

**Comment by pheyvaer** [comment]
Actually, it is not completely solved, because I still get the error. However, I think that it is because the broker is looking for the wrong file. It looks for `wikiner-en.nl-ner-model.ser.gz` while the file found in the image is `wikiner-nl-ner-model.ser.gz`.

**Comment by pheyvaer** [comment]
Yes :)

**Comment by jnehring** [comment]
documentation is already updated so this issue is finished
